yay -S --needed \
brave-bin \
google-chrome \
flatpak \
snapd \
libqalculate \
qalculate-qt \
virtualbox \
virtualbox-guest-iso \
qbittorrent \
jdownloader2 \
smplayer \
syncthing \
bitwarden \
nomacs-git \
anydesk-bin \
megasync-bin \
dropbox \
noisetorch \
obs-studio \
ventoy-bin \
deskreen \
ums \
foliate \
scrcpy \
guiscrcpy \
acetoneiso2 \
libreoffice-fresh \
libreoffice-extension-writer2latex \
libreoffice-extension-texmaths \
libreoffice-fresh-pt-br
