yay -S --needed --sudoloop "--noconfirm" \
brave-bin \
google-chrome \
flatpak \
snapd \
input-leap \
gnome-keyring \
libqalculate \
qalculate-qt \
virtualbox \
virtualbox-guest-iso \
ventoy-bin \
qbittorrent \
jdownloader2 \
syncthing \
bitwarden \
nomacs-git \
anydesk-bin \
megasync-bin \
dropbox \
noisetorch \
obs-studio \
iriunwebcam-bin \
droidcam \
deskreen \
foliate \
scrcpy \
guiscrcpy \
acetoneiso2 \
libreoffice-fresh \
libreoffice-extension-writer2latex \
libreoffice-extension-texmaths \
libreoffice-fresh-pt-br
